name: fluency
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  chewie: ^1.10.0
  device_preview: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  go_router: ^14.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod_annotation: ^2.6.1
  video_player: ^2.9.2

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          style: italic

  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/json/
